### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by antmar904** [stuxnet999/MemLabs#3]
Man am I having issues trying to pull the file/folder I think is needed in this challenge.  Any help moving forward with this is greatly appreciated.

**Comment by stuxnet999** [comment]
All you need to do is download the challenge file from MEGA.

This would the link to download the memory image of Lab 1 - https://mega.nz/#!6l4BhKIb!l8ATZoliB_ULlvlkESwkPiXAETJEF7p91Gf9CWuQI70

If you could elaborate the issue, it would help me see what it is.

**Comment by antmar904** [comment]
Hi, good day.

Sorry.  I've dl the file and I've been analyzing it with Volatility3.  I found some things but I'm stuck.  I don't want to give to much info via Github.  Maybe I can email you for some tips?

**Comment by stuxnet999** [comment]
I'm sorry I cannot give out the solution if that is what you're asking. Also there are many publicly available blogs which contain the solutions which I'm sure would answer your queries.

**Comment by antmar904** [comment]
Hi I was not asking for the solution just a hint or two to point me in the right direction...

**Comment by stuxnet999** [comment]
@antmar904 You can send an email to the one mentioned in the README or publicly available writeups would also help you I guess.

Thanks

**Comment by q2dg** [comment]
Just notice "filescan" plugin in Volatility3 doesn't outputs anything in all your Labs, so they can' t be solved as this step is often necessary to dump a file and so on. I don't know why this happens but it's a fact: using "filescan" in Volatility3 with your images does'nt output anything . You can prove it and will see

**Comment by stuxnet999** [comment]
Hey @q2dg the issue is not with the labs but maybe something to do with Vol3 itself. I am not really sure what the specific issue within the tool might be but the labs were released to be completely compatible with Vol2 and Vol3 was still in its developmental stages at that time.

So to solve the issue, you can try using Vol2.
