### ISSUE TITLE
What is the hash crack site for lab0?

### ISSUE THREAD

**Issue by Jpkie** [stuxnet999/MemLabs#4]
A surname;
![image](https://github.com/stuxnet999/MemLabs/assets/104114507/af19d980-558d-4b6a-a522-016d26f0426c)
I've been searching for over an hour and I can't find a site that can crack the hash value in lab0 =_=;

**Comment by Jpkie** [comment]
Although I just found out that I can use the mimikatz plugin to view it (sorry I'm still learning), I'm still curious to know what this site is.0_0

**Comment by Jpkie** [comment]
Although I just found out that I can use the mimikatz plugin to view it (sorry I'm still learning), I'm still curious to know what this site is.0_0

**Comment by stuxnet999** [comment]
Hello @Jpkie,

The website in the screenshot is https://md5decrypt.net/Ntlm. However since the challenge was released in 2018, this website no longer holds the plaintext of this hash. As you said the mimikatz plugin solves this issue.
